UI place details
mhughdo/3S-webapp pull request #13
Opened 2020-11-23 11:27 UTC by vuduc211299

2020-11-23 12:13 UTC, mhughdo commented on components/place/place_details/Amenities.tsx
> +            width="31.333%"
Không code thẳng các giá trị ở đây vì nó sẽ tạo ra sự không đồng nhất, tham khảo https://chakra-ui.com/docs/theming/theme để xem các giá trị mặc định của theme, nếu muôn thêm giá trị tuỳ ý mình thì có thể thêm vào file styles.ts

ví dụ marginTop: '12px' có thể sửa thành mt: 3, tương tự với lineHeight và các file khác 
![image](https://user-images.githubusercontent.com/15611134/99960774-e0e46500-2dbf-11eb-9f81-d02ea4e285cb.png)

2020-11-23 12:14 UTC, mhughdo commented on components/place/place_details/BookingForm.tsx
> +              </Text>
tương tự bên trên

2020-11-23 12:20 UTC, mhughdo commented on components/place/place_details/PlaceDetailsComponent.tsx
> +      <nav className={styles.place_details_nav} style={{display: showStickyNavBar ? "block" : "none"}}>
Nếu muốn ghi đè style của một element nào đó hoặc thêm custom style thì có thể dùng sx prop như này thay vì tạo 1 file scss mới 

![image](https://user-images.githubusercontent.com/15611134/99961119-7253d700-2dc0-11eb-90a8-08148d0fe8c9.png)

trong trường hợp này thì phải dùng chakra factory:
![image](https://user-images.githubusercontent.com/15611134/99961367-e2625d00-2dc0-11eb-9554-6817b9b7fa4c.png)

2020-11-23 12:21 UTC, mhughdo commented on components/place/place_details/PlaceIntro.tsx
> +                {truncated ? "Read more" : "Show less"}
Trang của mình để tiếng việt mà ta

2020-11-23 12:22 UTC, mhughdo requested changes
finish

2020-11-24 08:18 UTC, vuduc211299 commented
check lại PR đi, sửa rồi nhé !

2020-11-24 15:15 UTC, merged